# Generated by Django 3.2.9 on 2021-12-06 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grounds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=80)),
                ('postal', models.CharField(max_length=20)),
                ('area', models.CharField(max_length=80)),
                ('country', models.CharField(max_length=60)),
                ('opens', models.TimeField(blank=True, default=None)),
                ('closes', models.TimeField(blank=True, default=None)),
                ('changingrooms', models.BooleanField(blank=True, default=False)),
                ('parkingsituation', models.TextField(blank=True, default=None)),
                ('publictransportation', models.TextField(blank=True, default=None)),
                ('image', models.ImageField(default='default.jpg', upload_to='sportground_pics')),
            ],
        ),
        migrations.AddConstraint(
            model_name='grounds',
            constraint=models.UniqueConstraint(fields=('street', 'postal', 'country', 'type'), name='unique_ground'),
        ),
    ]
