# Generated by Django 3.2.9 on 2021-12-12 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportinggrounds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grounds',
            name='image',
            field=models.ImageField(default='sportground_pics/default.jpg', upload_to='sportground_pics'),
        ),
    ]
